FROM alpine:3.14
LABEL maintainer="Xueyuan, Jiang <alexxyjiang@gmail.com>"
ENV LANG="C.UTF-8" LC_ALL="C.UTF-8"
RUN apk update \
  && apk add --no-cache alpine-sdk curl git sudo vim zsh
RUN adduser -D -s /bin/zsh builder
RUN echo 'builder:M00n' | chpasswd
RUN echo 'builder ALL=(ALL) ALL' > /etc/sudoers.d/builder
RUN addgroup builder abuild
COPY .abuild.tar.gz /home/builder/.abuild.tar.gz
COPY .abuild/builder.rsa.pub /etc/apk/keys/builder.rsa.pub
USER builder
WORKDIR /home/builder
RUN tar zxvf .abuild.tar.gz \
  && rm .abuild.tar.gz
RUN zsh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
COPY .zshrc /home/builder/.zshrc
CMD [ "/bin/zsh" ]
