FROM alpine:3.20
LABEL maintainer="Xueyuan, Jiang <alexxyjiang@gmail.com>"
ENV LANG="C.UTF-8" LC_ALL="C.UTF-8"
RUN apk update \
  && apk add --no-cache alpine-sdk curl git sudo vim tzdata zsh
RUN adduser -D -s /bin/zsh builder
RUN echo 'builder:M00n' | chpasswd
RUN echo 'builder ALL=(ALL) ALL' > /etc/sudoers.d/builder
RUN addgroup builder abuild
COPY .abuild.tar.gz /home/builder/.abuild.tar.gz
COPY .abuild/builder.rsa.pub /etc/apk/keys/builder.rsa.pub
COPY .zshrc /home/builder/zshrc_template
USER builder
WORKDIR /home/builder
RUN tar zxvf .abuild.tar.gz \
  && rm .abuild.tar.gz
RUN env REPO="alexxyjiang/ohmyzsh" zsh -c "$(curl -fsSL https://raw.githubusercontent.com/alexxyjiang/ohmyzsh/master/tools/install.sh)"
RUN zsh zshrc_template && cp zshrc_template .zshrc && rm zshrc_template
CMD [ "/bin/zsh" ]
